### ISSUE TITLE
Memory use gradually increases

### ISSUE THREAD

**Issue by RJDan** [miracle-window-manager/miracle-wm#151]
Hi

I installed the snap and gave it a test run with no customisations. Even with no windows open (i.e. I log in and do nothing else) my memory usage increases slowly to the point that after about 5 minutes the system freezes and I need force a reboot. I have 40GB RAM.
On sway with many applications open and start-up systemd processes running, my RAM usage hovers at 6GB.

I am really excited to see this get to a workable state. 

OS: Ubuntu 24.04 LTS x86_64 
Host: ASUS TUF Gaming A15 FA506IH_FA506IH 1.0 
Kernel: 6.8.0-35-generic 
Uptime: 22 mins 
Packages: 2507 (dpkg), 91 (snap) 
Shell: bash 5.2.21 
Resolution: 1920x1080 
WM: sway 
Terminal: kitty 
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz 
GPU: AMD ATI Radeon RX Vega 6 
GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
Memory: 6655MiB / 39524MiB 

Let me know if you need any other info.

**Comment by mattkae** [comment]
Oof thanks for the info! That's great to know so that we can track it down. Is this consistent or sporadic for you? I'll check later today if I can repro on latest

**Comment by RJDan** [comment]
Hello 
It is consistent for the four times I tried over the last two months. I don't use miracle at all because of the issue.
I just try it once in a while to see if something has improved.

**Comment by mattkae** [comment]
Good to know. I will try and repro on my end and see what happens. Thanks for giving it a try and reporting the bug!

**Comment by RJDan** [comment]
Hello
I tested with the latest update, and the issue persists.
Just FYI.
```
refresh-date: yesterday at 19:27 CEST
channels:
  latest/stable:    0.3.0                2024-07-02 (227) 59MB classic
  latest/candidate: 0.3.0                2024-07-01 (227) 59MB classic
  latest/beta:      ↑                                          
  latest/edge:      262-mir2.17.0+dev248 2024-07-03 (232) 59MB classic
installed:          0.3.0                           (227) 59MB classic
```

**Comment by mattkae** [comment]
> Hello I tested with the latest update, and the issue persists. Just FYI.
> 
> ```
> refresh-date: yesterday at 19:27 CEST
> channels:
>   latest/stable:    0.3.0                2024-07-02 (227) 59MB classic
>   latest/candidate: 0.3.0                2024-07-01 (227) 59MB classic
>   latest/beta:      ↑                                          
>   latest/edge:      262-mir2.17.0+dev248 2024-07-03 (232) 59MB classic
> installed:          0.3.0                           (227) 59MB classic
> ```

Thanks! I have been seeing this spuriously too

**Comment by RJDan** [comment]
I tested it again, and I am now able to keep miraclewm running for more than 30min without any unexplained increase in memory.
yay!

```
snap-id:      feeK3fEyb12CsWiHDArUvU15Mr3PweFb
tracking:     latest/edge
refresh-date: today at 20:09 CEST
channels:
  latest/stable:    0.3.4         2024-08-27 (302) 59MB classic
  latest/candidate: 0.3.0         2024-07-01 (227) 59MB classic
  latest/beta:      ↑                                   
  latest/edge:      300-mir2.17.0 2024-09-04 (318) 59MB classic
installed:          300-mir2.17.0            (318) 59MB classic
```
